Add clear button
i-VRESSE/workflow-builder pull request #29
Opened 2022-02-08 16:21 UTC by rvhonorato

This PR addresses #14 by adding a button to clear the workflow.

Full disclaimer this is my **first ever** React PR so any feedback is appreciated 🤓

2022-02-11 09:39 UTC, sverhoeven requested changes
Great first react contribution.

I expected that when you load the example and press the clear button then in the text tab the text and file list would be empty, but the text still shows the global parameters and the file list shows files that where previously linked in the nodes.

Could you besides clearing the nodes array also clear the global and files objects? 

Clearing can be done to setting them to `{}`. Typescript will complain about empty object not having the correct type so you will need to use a typed assignment or cast

2022-02-11 09:39 UTC, sverhoeven commented on src/WorkflowClear.tsx
> +    <button className='btn btn-outline-danger' onClick={clearWorkflow}>
The wrapping of clearNodes is not needed. You can directly use clearNodes as onClick value.
```suggestion
  return (
    <button className='btn btn-outline-danger' onClick={clearNodes}>
```

2022-02-11 15:55 UTC, rvhonorato commented
> Clearing can be done to setting them to `{}`. Typescript will complain about empty object not having the correct type so you will need to use a typed assignment or cast

Thanks for the tip! 

It should now be clearing the globals and the files, please check if the implementation is ok

2022-02-15 08:22 UTC, sverhoeven requested changes
Almost there, can you also clear the files.

2022-02-15 08:22 UTC, sverhoeven commented on src/store.ts
> +      setGlobal(blankGlobals)
The files are not cleared yet
```suggestion
      setGlobal(blankGlobals)
      const blankFiles: IFiles = {}
      setFiles(blankFiles)
```

2022-02-15 08:22 UTC, sverhoeven commented on src/store.ts
> +    clearNodes () {
Name of function does not cover the functionality, can it be renamed to `clear()` or `clearWorkflow()`.

2022-02-15 12:25 UTC, rvhonorato commented on src/store.ts
> +      setGlobal(blankGlobals)
ops!

2022-02-21 09:18 UTC, sverhoeven approved these changes
Clearing the workflow now works completely.

Thanks for the contribution and feel free to merge it.

2022-02-21 11:47 UTC, merged

2022-02-21 11:48 UTC, rvhonorato commented
Thanks for the feedback @sverhoeven, I'll try to help with other issues 😄