Never make checkbox required
i-VRESSE/workflow-builder pull request #98
Opened 2022-07-21 07:53 UTC by sverhoeven

Fixes #67

2022-07-22 07:18 UTC, sverhoeven commented
This implementation blocks you from having a checkbox that must be checked to submit form. For example to agree to terms like a license.

2022-07-29 06:51 UTC, bvreede requested changes
Looks good! The bug in the workflow app has been fixed, the only thing I'm unsure about is the storybook; while the empty checkbox provided can be submitted without problems, any checkbox added does need to be ticked. Adding a checkbox then leaving it empty gives the error 

> .array[n] should be boolean

(where n is the number of the added checkbox).

+ small typo in the storybook :)

2022-07-29 06:51 UTC, bvreede commented on packages/form/src/IvresseCheckboxWidget.stories.tsx
> +UncheckedCheckboxInArrayIsSubmiteable.play = async () => {
typo fix
```suggestion
export const UncheckedCheckboxInArrayIsSubmittable = CheckboxArray.bind({})
UncheckedCheckboxInArrayIsSubmittable.play = async () => {
```

2022-07-29 08:03 UTC, bvreede approved these changes

2022-07-29 08:04 UTC, sverhoeven commented
Thanks for reviewing

2022-07-29 08:04 UTC, merged